"""Add total_game_score to User

Revision ID: 15478343affe
Revises: f491e8d8c69c
Create Date: 2026-01-12 11:16:50.317946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15478343affe'
down_revision = 'f491e8d8c69c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_game_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('total_game_score')

    # ### end Alembic commands ###
