"""add email confirmation fields

Revision ID: 30736e3a0143
Revises: 367c4eb99a6a
Create Date: 2026-01-16 12:59:11.268738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30736e3a0143'
down_revision = '367c4eb99a6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_confirmed', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('confirmed_on', sa.DateTime(), nullable=True))
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('confirmed_on')
        batch_op.drop_column('email_confirmed')

    # ### end Alembic commands ###
