"""Add interests to User model

Revision ID: 5d9450f4aec8
Revises: a4e4174ad171
Create Date: 2025-09-16 12:01:02.071413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d9450f4aec8'
down_revision = 'a4e4174ad171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interests', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('interests')

    # ### end Alembic commands ###
