"""Make native_language and learning_language nullable in User model

Revision ID: a4e4174ad171
Revises: 3e89aa1514ae
Create Date: 2025-09-16 11:34:01.937313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4e4174ad171'
down_revision = '3e89aa1514ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('native_language',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('learning_language',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('learning_language',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('native_language',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
