"""Migration with nullable fields

Revision ID: f491e8d8c69c
Revises: 
Create Date: 2026-01-12 10:16:54.734461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f491e8d8c69c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interactive_game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('level_title', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('word', sa.String(length=100), nullable=True))
        batch_op.alter_column('target_language',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('correct_word')
        batch_op.drop_column('incorrect_words')
        batch_op.drop_column('title')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_completed_level', sa.Integer(), nullable=True))
        batch_op.drop_column('last_completed_game_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_completed_game_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('last_completed_level')

    with op.batch_alter_table('interactive_game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('incorrect_words', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('correct_word', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.alter_column('target_language',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('word')
        batch_op.drop_column('level_title')
        batch_op.drop_column('level_id')

    # ### end Alembic commands ###
